services:
  - type: web
    name: fluxobet-server
    env: node
    rootDir: server
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CORS_ORIGINS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: fluxobet
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_SHORTCODE
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_INITIATOR
        sync: false
      - key: MPESA_CALLBACK_BASE_URL
        sync: false
      - key: MPESA_ENVIRONMENT
        value: sandbox
      - key: MPESA_COUNTRY_CODE
        value: '258'
  - type: static_site
    name: fluxobet-web
    rootDir: web
    plan: starter
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
      - key: VITE_SOCKET_URL
        sync: false
      - key: VITE_SOCKET_PATH
        value: /socket.io
